
import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ru';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Translations = {
  en: {
    adminPanelTutorial: 'Admin Panel Tutorial',
    quickStart: 'Quick Start',
    detailedGuide: 'Detailed Guide',
    casinoSetup: 'Casino Setup',
    cardsPayments: 'Cards Payments',
    askQuestion: 'Ask a Question',
    howToAddCity: 'How to add City',
    howToAddDistrict: 'How to add District',
    howToAddCourier: 'How to add Courier',
    howToCreateProductGroup: 'How to create Product Group',
    howToCreateProductTypes: 'How to create Product Types',
    howToAddAddress: 'How to add Address',
    howToAddBots: 'How to add Bots',
    oneTimeDiscounts: 'One-time Discounts',
    btcCashout: 'BTC Cashout',
    balanceHistory: 'Balance History',
    internalChats: 'Internal Chats',
    reviews: 'Reviews',
    marketing: 'Marketing',
    merchants: 'Merchants',
    masterKlad: 'Master Klad',
    customBot: 'Custom Bot',
    workers: 'Workers',
    clients: 'Clients',
    purchases: 'Purchases',
    balanceTopUps: 'Balance Top Ups',
    messages: 'Messages',
    web: 'Web',
    couriersSalary: 'Couriers Salary',
    usdt: 'USDT',
    partnersExchangers: 'Partners Exchangers',
    welcome: 'Welcome to Admin Panel Tutorial',
    selectTopic: 'Select a topic to get started:',
    quickStartShortDesc: 'Get up and running quickly with essential setup steps',
    detailedGuideShortDesc: 'Comprehensive guides for all admin panel features',
    casinoSetupShortDesc: 'Set up and configure the casino module',
    cardsPaymentsShortDesc: 'Configure and manage payment card systems',
    english: 'English',
    russian: 'Russian',
    languageSelector: 'Language',
    
    // Quick Start page content
    quickStartDescription: 'This quick start guide will help you set up and configure your admin panel in just a few steps. Follow these instructions to get your system up and running quickly.',
    
    quickStartPoint1: 'Initial Setup and Configuration',
    quickStartPoint1Note1: 'Log in to your admin panel using the credentials provided by your system administrator.',
    quickStartPoint1Note2: 'Navigate to Settings > General to configure your site name, timezone, and default language.',
    quickStartPoint1Note3: 'Set up your company profile with accurate contact information.',
    quickStartPoint1Note4: 'Configure email settings to ensure proper notification delivery.',
    quickStartPoint1Note5: 'Set up backup schedule and security settings.',
    quickStartPoint1Note6: 'Configure user roles and permissions based on your organizational structure.',
    quickStartPoint1Note7: 'Review and adjust system-wide settings for optimal performance.',
    quickStartPoint1Note8: 'Save your configuration and restart the system if prompted.',
    
    quickStartPoint2: 'User Management',
    quickStartPoint2Note1: 'Create administrator accounts for key team members.',
    quickStartPoint2Note2: 'Set appropriate permission levels for each user role.',
    quickStartPoint2Note3: 'Configure two-factor authentication for enhanced security.',
    quickStartPoint2Note4: 'Set password policies that comply with your security requirements.',
    quickStartPoint2Note5: 'Create user groups to simplify permission management.',
    quickStartPoint2Note6: 'Test each user role to ensure proper access control.',
    quickStartPoint2Note7: 'Document the user management structure for future reference.',
    quickStartPoint2Note8: 'Train your team on security best practices.',
    
    quickStartPoint3: 'Location Management',
    quickStartPoint3Note1: 'Add your primary city locations in the Cities section.',
    quickStartPoint3Note2: 'Set up districts within each city for better organization.',
    quickStartPoint3Note3: 'Configure delivery zones and associated fees if applicable.',
    quickStartPoint3Note4: 'Add physical addresses for your warehouses and operational centers.',
    quickStartPoint3Note5: 'Set up geofencing parameters for delivery area limitations.',
    quickStartPoint3Note6: 'Configure location-based taxes and regulations compliance.',
    quickStartPoint3Note7: 'Test the location filtering in your admin dashboard.',
    quickStartPoint3Note8: 'Create location-specific reports for performance tracking.',
    
    quickStartPoint4: 'Product Catalog Setup',
    quickStartPoint4Note1: 'Create product groups to organize your inventory.',
    quickStartPoint4Note2: 'Define product types with appropriate attributes and fields.',
    quickStartPoint4Note3: 'Add your initial inventory with complete descriptions and pricing.',
    quickStartPoint4Note4: 'Upload high-quality images for all products.',
    quickStartPoint4Note5: 'Set up inventory tracking and stock alerts.',
    quickStartPoint4Note6: 'Configure product variants if needed (sizes, colors, etc.).',
    quickStartPoint4Note7: 'Set up pricing tiers for different customer types.',
    quickStartPoint4Note8: 'Review your entire catalog for consistency and completeness.',
    
    quickStartPoint5: 'Payment Configuration',
    quickStartPoint5Note1: 'Configure cryptocurrency payment options (BTC, USDT).',
    quickStartPoint5Note2: 'Set up card payment processors and APIs.',
    quickStartPoint5Note3: 'Configure payment security settings and fraud protection.',
    quickStartPoint5Note4: 'Test all payment flows thoroughly in a sandbox environment.',
    quickStartPoint5Note5: 'Set up automatic payment receipts and notifications.',
    quickStartPoint5Note6: 'Configure payment refund policies and procedures.',
    quickStartPoint5Note7: 'Set up automatic reconciliation for accounting.',
    quickStartPoint5Note8: 'Document payment troubleshooting procedures for your team.',
    
    quickStartPoint6: 'Bot Integration',
    quickStartPoint6Note1: 'Configure the standard bot templates for your business needs.',
    quickStartPoint6Note2: 'Set up custom bot responses and conversation flows.',
    quickStartPoint6Note3: 'Connect your bots to required APIs and data sources.',
    quickStartPoint6Note4: 'Configure bot notification settings and escalation paths.',
    quickStartPoint6Note5: 'Set up automated responses for common queries.',
    quickStartPoint6Note6: 'Test bot interactions across different scenarios.',
    quickStartPoint6Note7: 'Configure analytics to track bot performance and usage.',
    quickStartPoint6Note8: 'Set up regular maintenance and update schedules for bots.',
    
    quickStartPoint7: 'Courier Management',
    quickStartPoint7Note1: 'Add courier accounts with proper verification documentation.',
    quickStartPoint7Note2: 'Configure courier zones and service areas.',
    quickStartPoint7Note3: 'Set up courier payment schedules and commission rates.',
    quickStartPoint7Note4: 'Configure the courier mobile application settings.',
    quickStartPoint7Note5: 'Set up performance metrics and quality controls.',
    quickStartPoint7Note6: 'Create courier training materials and guidelines.',
    quickStartPoint7Note7: 'Configure automatic task assignment algorithms.',
    quickStartPoint7Note8: 'Set up courier status monitoring and alerts.',
    
    quickStartPoint8: 'Reporting System',
    quickStartPoint8Note1: 'Configure daily sales and activity reports.',
    quickStartPoint8Note2: 'Set up financial reports and payment reconciliation.',
    quickStartPoint8Note3: 'Create inventory and product performance reports.',
    quickStartPoint8Note4: 'Set up courier and delivery performance analytics.',
    quickStartPoint8Note5: 'Configure customer activity and retention reports.',
    quickStartPoint8Note6: 'Set up automatic report generation and distribution.',
    quickStartPoint8Note7: 'Create custom dashboards for different team roles.',
    quickStartPoint8Note8: 'Set up alert thresholds for key performance indicators.',
    
    quickStartPoint9: 'Marketing Tools',
    quickStartPoint9Note1: 'Configure discount and promotion system settings.',
    quickStartPoint9Note2: 'Set up email marketing integration and templates.',
    quickStartPoint9Note3: 'Configure customer loyalty program parameters.',
    quickStartPoint9Note4: 'Set up referral system bonuses and tracking.',
    quickStartPoint9Note5: 'Create marketing campaign schedules and automation.',
    quickStartPoint9Note6: 'Configure A/B testing tools for marketing optimization.',
    quickStartPoint9Note7: 'Set up marketing performance analytics.',
    quickStartPoint9Note8: 'Create re-engagement campaigns for inactive customers.',
    
    quickStartPoint10: 'Security Configuration',
    quickStartPoint10Note1: 'Review and strengthen all default security settings.',
    quickStartPoint10Note2: 'Configure IP blocking and access restrictions.',
    quickStartPoint10Note3: 'Set up activity logging and security alerts.',
    quickStartPoint10Note4: 'Configure data encryption settings for sensitive information.',
    quickStartPoint10Note5: 'Set up regular security scan schedules.',
    quickStartPoint10Note6: 'Create incident response procedures and documentation.',
    quickStartPoint10Note7: 'Configure data retention and protection policies.',
    quickStartPoint10Note8: 'Schedule regular security audits and compliance checks.',
    
    quickStartPoint11: 'Communication System',
    quickStartPoint11Note1: 'Set up internal chat system groups and permissions.',
    quickStartPoint11Note2: 'Configure customer notification preferences.',
    quickStartPoint11Note3: 'Set up automatic message templates for common scenarios.',
    quickStartPoint11Note4: 'Configure message retention and archiving policies.',
    quickStartPoint11Note5: 'Set up messaging analytics and response time tracking.',
    quickStartPoint11Note6: 'Configure integration with external messaging services.',
    quickStartPoint11Note7: 'Set up emergency broadcast capabilities.',
    quickStartPoint11Note8: 'Test all communication channels thoroughly.',
    
    quickStartPoint12: 'Merchant Integration',
    quickStartPoint12Note1: 'Add merchant accounts with proper documentation.',
    quickStartPoint12Note2: 'Configure merchant commission structures.',
    quickStartPoint12Note3: 'Set up merchant portal access and permissions.',
    quickStartPoint12Note4: 'Configure product availability by merchant.',
    quickStartPoint12Note5: 'Set up merchant performance analytics.',
    quickStartPoint12Note6: 'Configure merchant payment schedules and methods.',
    quickStartPoint12Note7: 'Create merchant support channels and resources.',
    quickStartPoint12Note8: 'Set up merchant verification and quality control processes.',
    
    quickStartPoint13: 'System Testing',
    quickStartPoint13Note1: 'Conduct end-to-end testing of all major system flows.',
    quickStartPoint13Note2: 'Test all integration points with external systems.',
    quickStartPoint13Note3: 'Conduct load testing to ensure system stability.',
    quickStartPoint13Note4: 'Perform security testing and vulnerability assessment.',
    quickStartPoint13Note5: 'Test backup and recovery procedures.',
    quickStartPoint13Note6: 'Conduct user acceptance testing with key stakeholders.',
    quickStartPoint13Note7: 'Document any issues found and their resolutions.',
    quickStartPoint13Note8: 'Create a system monitoring plan for ongoing operations.',
  },
  ru: {
    adminPanelTutorial: 'Руководство по админ-панели',
    quickStart: 'Быстрый Старт',
    detailedGuide: 'Подробное руководство',
    casinoSetup: 'Настройка Казино',
    cardsPayments: 'Оплата картами',
    askQuestion: 'Задать вопрос',
    howToAddCity: 'Как добавить город',
    howToAddDistrict: 'Как добавить район',
    howToAddCourier: 'Как добавить курьера',
    howToCreateProductGroup: 'Как создать группу товаров',
    howToCreateProductTypes: 'Как создать типы товаров',
    howToAddAddress: 'Как добавить адрес',
    howToAddBots: 'Как добавить ботов',
    oneTimeDiscounts: 'Разовые скидки на товары',
    btcCashout: 'Обнал BTC',
    balanceHistory: 'История изменения балансов',
    internalChats: 'Внутренние чаты',
    reviews: 'Отзывы',
    marketing: 'Маркетинг',
    merchants: 'Мерчанты',
    masterKlad: 'Мастер Клад',
    customBot: 'Кастомный бот',
    workers: 'Работники',
    clients: 'Клиенты',
    purchases: 'Покупки',
    balanceTopUps: 'Пополнения баланса',
    messages: 'Сообщения',
    web: 'Веб',
    couriersSalary: 'Зарплата курьеров',
    usdt: 'USDT',
    partnersExchangers: 'Партнеры обменники',
    welcome: 'Добро пожаловать в руководство по админ-панели',
    selectTopic: 'Выберите тему для начала:',
    quickStartShortDesc: 'Быстрое начало работы с основными шагами настройки',
    detailedGuideShortDesc: 'Подробные руководства по всем функциям админ-панели',
    casinoSetupShortDesc: 'Настройка и конфигурация модуля казино',
    cardsPaymentsShortDesc: 'Настройка и управление системами платежных карт',
    english: 'Английский',
    russian: 'Русский',
    languageSelector: 'Язык',
    
    // Quick Start page content
    quickStartDescription: 'Это руководство по быстрому старту поможет вам настроить и сконфигурировать вашу админ-панель всего за несколько шагов. Следуйте этим инструкциям, чтобы быстро запустить вашу систему.',
    
    quickStartPoint1: 'Начальная настройка и конфигурация',
    quickStartPoint1Note1: 'Войдите в админ-панель, используя учетные данные, предоставленные вашим системным администратором.',
    quickStartPoint1Note2: 'Перейдите в Настройки > Общие для настройки названия сайта, часового пояса и языка по умолчанию.',
    quickStartPoint1Note3: 'Настройте профиль компании с точной контактной информацией.',
    quickStartPoint1Note4: 'Настройте параметры электронной почты для обеспечения правильной доставки уведомлений.',
    quickStartPoint1Note5: 'Настройте расписание резервного копирования и параметры безопасности.',
    quickStartPoint1Note6: 'Настройте роли пользователей и разрешения в соответствии с вашей организационной структурой.',
    quickStartPoint1Note7: 'Просмотрите и скорректируйте общесистемные настройки для оптимальной производительности.',
    quickStartPoint1Note8: 'Сохраните конфигурацию и перезапустите систему, если будет предложено.',
    
    quickStartPoint2: 'Управление пользователями',
    quickStartPoint2Note1: 'Создайте учетные записи администраторов для ключевых членов команды.',
    quickStartPoint2Note2: 'Установите соответствующие уровни разрешений для каждой роли пользователя.',
    quickStartPoint2Note3: 'Настройте двухфакторную аутентификацию для повышения безопасности.',
    quickStartPoint2Note4: 'Установите политики паролей, соответствующие вашим требованиям безопасности.',
    quickStartPoint2Note5: 'Создайте группы пользователей для упрощения управления разрешениями.',
    quickStartPoint2Note6: 'Протестируйте каждую роль пользователя, чтобы обеспечить надлежащий контроль доступа.',
    quickStartPoint2Note7: 'Документируйте структуру управления пользователями для дальнейшего использования.',
    quickStartPoint2Note8: 'Обучите вашу команду лучшим практикам безопасности.',
    
    quickStartPoint3: 'Управление местоположениями',
    quickStartPoint3Note1: 'Добавьте основные локации городов в разделе Города.',
    quickStartPoint3Note2: 'Настройте районы в каждом городе для лучшей организации.',
    quickStartPoint3Note3: 'Настройте зоны доставки и соответствующие тарифы, если применимо.',
    quickStartPoint3Note4: 'Добавьте физические адреса для ваших складов и операционных центров.',
    quickStartPoint3Note5: 'Настройте параметры геозон для ограничений зон доставки.',
    quickStartPoint3Note6: 'Настройте локальные налоги и соответствие нормативным требованиям.',
    quickStartPoint3Note7: 'Протестируйте фильтрацию по местоположению в панели администратора.',
    quickStartPoint3Note8: 'Создайте отчеты по конкретным местоположениям для отслеживания производительности.',
    
    quickStartPoint4: 'Настройка каталога продуктов',
    quickStartPoint4Note1: 'Создайте группы продуктов для организации вашего инвентаря.',
    quickStartPoint4Note2: 'Определите типы продуктов с соответствующими атрибутами и полями.',
    quickStartPoint4Note3: 'Добавьте начальный инвентарь с полными описаниями и ценами.',
    quickStartPoint4Note4: 'Загрузите качественные изображения для всех продуктов.',
    quickStartPoint4Note5: 'Настройте отслеживание инвентаря и оповещения о запасах.',
    quickStartPoint4Note6: 'Настройте варианты продуктов при необходимости (размеры, цвета и т.д.).',
    quickStartPoint4Note7: 'Настройте ценовые уровни для разных типов клиентов.',
    quickStartPoint4Note8: 'Проверьте весь каталог на согласованность и полноту.',
    
    quickStartPoint5: 'Настройка оплаты',
    quickStartPoint5Note1: 'Настройте варианты оплаты криптовалютой (BTC, USDT).',
    quickStartPoint5Note2: 'Настройте процессоры карточных платежей и API.',
    quickStartPoint5Note3: 'Настройте параметры безопасности платежей и защиту от мошенничества.',
    quickStartPoint5Note4: 'Тщательно протестируйте все платежные потоки в тестовой среде.',
    quickStartPoint5Note5: 'Настройте автоматические квитанции и уведомления об оплате.',
    quickStartPoint5Note6: 'Настройте политики и процедуры возврата платежей.',
    quickStartPoint5Note7: 'Настройте автоматическую сверку для бухгалтерского учета.',
    quickStartPoint5Note8: 'Документируйте процедуры устранения проблем с платежами для вашей команды.',
    
    quickStartPoint6: 'Интеграция ботов',
    quickStartPoint6Note1: 'Настройте стандартные шаблоны ботов в соответствии с потребностями вашего бизнеса.',
    quickStartPoint6Note2: 'Настройте пользовательские ответы ботов и потоки разговоров.',
    quickStartPoint6Note3: 'Подключите ваших ботов к необходимым API и источникам данных.',
    quickStartPoint6Note4: 'Настройте параметры уведомлений ботов и пути эскалации.',
    quickStartPoint6Note5: 'Настройте автоматические ответы на частые запросы.',
    quickStartPoint6Note6: 'Протестируйте взаимодействие с ботами в различных сценариях.',
    quickStartPoint6Note7: 'Настройте аналитику для отслеживания производительности и использования ботов.',
    quickStartPoint6Note8: 'Настройте регулярное обслуживание и график обновления ботов.',
    
    quickStartPoint7: 'Управление курьерами',
    quickStartPoint7Note1: 'Добавьте учетные записи курьеров с надлежащей проверочной документацией.',
    quickStartPoint7Note2: 'Настройте зоны курьеров и области обслуживания.',
    quickStartPoint7Note3: 'Настройте графики оплаты и ставки комиссионных для курьеров.',
    quickStartPoint7Note4: 'Настройте параметры мобильного приложения курьера.',
    quickStartPoint7Note5: 'Настройте показатели эффективности и контроль качества.',
    quickStartPoint7Note6: 'Создайте учебные материалы и руководства для курьеров.',
    quickStartPoint7Note7: 'Настройте алгоритмы автоматического назначения задач.',
    quickStartPoint7Note8: 'Настройте мониторинг статуса курьеров и оповещения.',
    
    quickStartPoint8: 'Система отчетности',
    quickStartPoint8Note1: 'Настройте ежедневные отчеты о продажах и активности.',
    quickStartPoint8Note2: 'Настройте финансовые отчеты и сверку платежей.',
    quickStartPoint8Note3: 'Создайте отчеты по инвентаризации и эффективности продуктов.',
    quickStartPoint8Note4: 'Настройте аналитику производительности курьеров и доставки.',
    quickStartPoint8Note5: 'Настройте отчеты по активности и удержанию клиентов.',
    quickStartPoint8Note6: 'Настройте автоматическое создание и распространение отчетов.',
    quickStartPoint8Note7: 'Создайте пользовательские панели для различных ролей в команде.',
    quickStartPoint8Note8: 'Настройте пороговые значения оповещений для ключевых показателей эффективности.',
    
    quickStartPoint9: 'Маркетинговые инструменты',
    quickStartPoint9Note1: 'Настройте параметры системы скидок и акций.',
    quickStartPoint9Note2: 'Настройте интеграцию и шаблоны электронного маркетинга.',
    quickStartPoint9Note3: 'Настройте параметры программы лояльности клиентов.',
    quickStartPoint9Note4: 'Настройте бонусы и отслеживание реферальной системы.',
    quickStartPoint9Note5: 'Создайте графики маркетинговых кампаний и автоматизацию.',
    quickStartPoint9Note6: 'Настройте инструменты A/B-тестирования для оптимизации маркетинга.',
    quickStartPoint9Note7: 'Настройте аналитику эффективности маркетинга.',
    quickStartPoint9Note8: 'Создайте кампании по повторному привлечению неактивных клиентов.',
    
    quickStartPoint10: 'Конфигурация безопасности',
    quickStartPoint10Note1: 'Просмотрите и усильте все настройки безопасности по умолчанию.',
    quickStartPoint10Note2: 'Настройте блокировку IP и ограничения доступа.',
    quickStartPoint10Note3: 'Настройте журналирование активности и оповещения безопасности.',
    quickStartPoint10Note4: 'Настройте параметры шифрования данных для конфиденциальной информации.',
    quickStartPoint10Note5: 'Настройте регулярные графики проверки безопасности.',
    quickStartPoint10Note6: 'Создайте процедуры реагирования на инциденты и документацию.',
    quickStartPoint10Note7: 'Настройте политики хранения и защиты данных.',
    quickStartPoint10Note8: 'Запланируйте регулярные аудиты безопасности и проверки соответствия.',
    
    quickStartPoint11: 'Коммуникационная система',
    quickStartPoint11Note1: 'Настройте группы и разрешения для системы внутреннего чата.',
    quickStartPoint11Note2: 'Настройте предпочтения уведомлений клиентов.',
    quickStartPoint11Note3: 'Настройте шаблоны автоматических сообщений для типовых ситуаций.',
    quickStartPoint11Note4: 'Настройте политики хранения и архивирования сообщений.',
    quickStartPoint11Note5: 'Настройте аналитику сообщений и отслеживание времени отклика.',
    quickStartPoint11Note6: 'Настройте интеграцию с внешними службами обмена сообщениями.',
    quickStartPoint11Note7: 'Настройте возможности экстренного вещания.',
    quickStartPoint11Note8: 'Тщательно протестируйте все каналы связи.',
    
    quickStartPoint12: 'Интеграция мерчантов',
    quickStartPoint12Note1: 'Добавьте учетные записи мерчантов с соответствующей документацией.',
    quickStartPoint12Note2: 'Настройте структуры комиссионных для мерчантов.',
    quickStartPoint12Note3: 'Настройте доступ и разрешения портала мерчантов.',
    quickStartPoint12Note4: 'Настройте доступность продуктов по мерчантам.',
    quickStartPoint12Note5: 'Настройте аналитику производительности мерчантов.',
    quickStartPoint12Note6: 'Настройте графики и методы оплаты мерчантам.',
    quickStartPoint12Note7: 'Создайте каналы поддержки и ресурсы для мерчантов.',
    quickStartPoint12Note8: 'Настройте процессы проверки и контроля качества мерчантов.',
    
    quickStartPoint13: 'Тестирование системы',
    quickStartPoint13Note1: 'Проведите сквозное тестирование всех основных системных потоков.',
    quickStartPoint13Note2: 'Протестируйте все точки интеграции с внешними системами.',
    quickStartPoint13Note3: 'Проведите нагрузочное тестирование для обеспечения стабильности системы.',
    quickStartPoint13Note4: 'Выполните тестирование безопасности и оценку уязвимостей.',
    quickStartPoint13Note5: 'Протестируйте процедуры резервного копирования и восстановления.',
    quickStartPoint13Note6: 'Проведите приемочное тестирование с ключевыми заинтересованными сторонами.',
    quickStartPoint13Note7: 'Задокументируйте все обнаруженные проблемы и их решения.',
    quickStartPoint13Note8: 'Создайте план мониторинга системы для текущих операций.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
